package sootproject.myexpression;

public enum OperationType {
	ADD, SUB, MUL, DIV, MOD, EQUAL, CONTAINS, NAEQ, NEG, LT, LE, GT, GE, LENGTH, STARTWITH, ENDWITH, HASH, UPPERCASE, LOWERCASE, AND, OR, XOR, APPEND, VALUEOF, PRASEINT, ORDINAL, SELECT, PUT, GETFIELD, SETFIELD, DEFAULT, SAME, NAME
}
